name: Deploy to S3

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Sync files to S3
        run: |
          aws s3 sync website/ s3://lladrayo-static-site-12345 --delete
          echo "✅ Website deployed at: http://lladrayo-static-site-12345.s3-website-ap-southeast-1.amazonaws.com"
