name: Deploy to S3

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- 1) Check that secrets exist (without revealing them) ---
      - name: Check secrets are available
        env:
          AKID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SKEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          [ -n "$AKID" ] || (echo "::error::Missing secret AWS_ACCESS_KEY_ID"; exit 1)
          [ -n "$SKEY" ] || (echo "::error::Missing secret AWS_SECRET_ACCESS_KEY"; exit 1)
          case "$AKID" in
            AKIA*|ASIA*) echo "Secret format looks OK ✅";;
            *) echo "::warning::AWS_ACCESS_KEY_ID does not start with AKIA/ASIA (double-check value)";;
          esac

      # --- 2) Configure AWS credentials using the official action ---
      - name: Configure AWS credentials (action)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # --- 3) Prove the identity (will fail if creds aren't loaded) ---
      - name: Who am I?
        run: aws sts get-caller-identity

      # --- 4) Deploy ---
      - name: Sync files to S3
        run: |
          aws s3 sync website/ s3://<YOUR-BUCKET-NAME> --delete
          echo "Deployed to: http://<YOUR-BUCKET-NAME>.s3-website-ap-southeast-1.amazonaws.com"
