name: Deploy to S3

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check secrets are available
        env:
          AKID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SKEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          [ -n "$AKID" ] || (echo "::error::Missing secret AWS_ACCESS_KEY_ID"; exit 1)
          [ -n "$SKEY" ] || (echo "::error::Missing secret AWS_SECRET_ACCESS_KEY"; exit 1)
          echo "Secrets present ✅"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2   # Sydney (matches your CloudFormation region)

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Sync repo to S3
        env:
          BUCKET: staticsitestack-static-site   # your actual bucket name
        run: |
          aws s3 sync . s3://$BUCKET --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "s3-static-site.yaml" \
            --exclude "template.yml" \
            --exclude "README.md"
          echo "Deployed to: http://$BUCKET.s3-website-ap-southeast-2.amazonaws.com"
